### ISSUE TITLE
python script to process the exported srt file 

### ISSUE THREAD

**Issue by hasauino** [IbraheemTuffaha/sonix.ai-assistant#1]
السلام عليكم ابراهيم
أولا شغلكم أنت و علي جميل ما شاء الله ..

حبيت أشارك بسكريبت بايثون كتبته عشان يشيل الهاشتاقات و يدمج ال
subtitles

أظن ممكن خلصتو هاي الخطوة... لكن احتياطا هاض رابط السكريبت:
[fixsrt.py](https://github.com/hasauino/fixsrt/blob/master/bin/fixsrt.py)

```
fixsrt.py file.srt
```

**Comment by IbraheemTuffaha** [comment]
وعليكم السلام
بالنسبة للـ
script
وين المطلوب تكون؟
أنا فهمت أنه سيتم إضافة هذا إلى برنامج ما يقوم ببنائه أحد.

**Comment by hasauino** [comment]
أنا فكرت أنت الي شغال على البرنامج الي بعالج الملفات بعد ال
export

خلص معناتو رح أتواصل مع الشب الثاني الي شغال على معالجة الملفات

**Comment by IbraheemTuffaha** [comment]
خيراً خيراً
