### ISSUE TITLE
count update only for current paragraph (where the text cursor -caret- is)

### ISSUE THREAD

**Issue by hasauino** [IbraheemTuffaha/sonix.ai-assistant#6]
Instead of updating the count of all paragraphs, only update current paragraph that's being edited by the user.

- Problem: I couldn't find a way to know which paragraph has the text cursor. We cannot just rely on the paragraph associated with current position of the video time bar, since the position of the text cursor is not related to the time bar.

- Suggestion 1:
get the paragraph that corresponds to the current position of the video time bar (already done in the update caption), then update the count of that paragraph and also the count of the five paragraphs after and before (the user is most likely in one of these paragraphs).

- Suggestion 2:
Keep both options available to use: we can add a small UI (a switch) using it, the user can choose between "update always", or "update on play"... (I'm going with this direction). Another switch can be added turn ON/OFF video captions

**Comment by hasauino** [comment]
Example on suggestion 2:

![Screenshot from 2020-02-15 02-05-50](https://user-images.githubusercontent.com/16976625/74578935-bb583e80-4f97-11ea-8520-5218db4e1632.png)

**Comment by hasauino** [comment]
Suggestion 2 is implemented in this    [PR](#7)

**Comment by hasauino** [comment]
Check this PR #7, it implements suggestion 2

**Comment by Dev-Now** [comment]
@hasauino to reiterate my suggestion (explained in Telegram):
Make interactive character count active for visible paragraphs only.
It starts at initialization (page opened) and counts for visible paragraphs, then refreshes for visible paragraphs upon scroll events.
